### ISSUE TITLE
Test h1d using in-house Hi-C dataset cause error

### ISSUE THREAD

**Issue by Linhua-Sun** [wangjk321/HiC1Dmetrics#1]
Hi:
    This is Linhua Sun. I have read h1d after reading recently published BIB paper. When I tried to used, it caused errors. I have tried two different cooler files (each with chromosome name 1 2 3, another with chromosome name Gm01 Gm02). Both are failed.
    I have attached the command lines and errors.
**CML:**
    `h1d one -o PP.txt --datatype cool --gt Gm.size ISC 40K.cool 20000 Gm01`

**Error:**

```
Start dump matrix from cool file
Traceback (most recent call last):
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Gm01'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/cooler/util.py", line 170, in parse_region
    clen = chromsizes[chrom] if chromsizes is not None else None
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'Gm01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linhua/anaconda3/bin/cooler", line 8, in <module>
    sys.exit(cli())
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/cooler/cli/_util.py", line 197, in decorated
    func(*args, **kwargs)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/cooler/cli/dump.py", line 339, in dump
    parse_region(range, c.chromsizes),
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/cooler/util.py", line 172, in parse_region
    raise ValueError("Unknown sequence label: {}".format(chrom))
ValueError: Unknown sequence label: Gm01
Traceback (most recent call last):
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Gm01'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/h1d/extract/convert_JuicerDump_to_dense.py", line 35, in <module>
    chrlen = genometable.loc[chr]
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1124, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1073, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 3739, in xs
    loc = index.get_loc(key)
  File "/home/linhua/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'Gm01'
Finish dump
Calculating 1D metrics for one sample
Error: Please use the right mode
```

**Genome table** 

```
GM01	56831624
GM02	48577505
GM03	45779781
GM04	52389146
GM05	42234498
GM06	51416486
GM07	44630646
GM08	47837940
GM09	50189764
GM10	51566898
GM11	34766867
GM12	40091314
GM13	45874162
GM14	49042192
GM15	51756343
GM16	37887014
GM17	41641366
GM18	58018742
GM19	50746916
GM20	47904181
```

**Comment by wangjk321** [comment]
h1d assume the chromosome name as "chr1", "chr2"..etc, you should check the `cooler dump -t chroms $coolfile`. If the chromosome name is truly 'GM01' etc, it is better to prepare contact matrix by your self, then use `matrix` mode.

**Comment by Linhua-Sun** [comment]
Thanks for your advice.

**Comment by Linhua-Sun** [comment]
However, the chromosome names are usually different (with or without chr, Chr, and others). Is it possible to handle the problems Inside `hd1`. Thanks.

**Comment by Linhua-Sun** [comment]
Thanks. The problem were solved by cooler API (change other chr name into chr1).
